In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Retail_Dataset_Modified.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   str
 1   Store_Name             5171 non-null   str
 2   Brand_Name             5171 non-null   str
 3   Store_Type             5171 non-null   str
 4   City                   5109 non-null   str
 5   City_Tier              5171 non-null   str
 6   Product_Name           5098 non-null   str
 7   Category               5171 non-null   str
 8   Sub_Category           5171 non-null   str
 9   Product_Stage          5171 non-null   str
 10  Quantity_Available     5171 non-null   str
 11  Units_Sold             5171 non-null   str
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   str
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   str
 20  Sales_Channel          5171 non-null   str
 21  Payment_Method         5171 non-null   str
 22  Supplier               5103 non-null   str
 23  Supplier_Rating        5171 non-null   str
 24  Promotion_Type         5171 non-null   str
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   str
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   str
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   str
 40  Weather_Impact         5171 non-null   str
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   str
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   str
 46  Season                 5171 non-null   str
dtypes: float64(11), int64(10), str(26)
memory usage: 1.9 MB

In [5]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [6]:
df['Quantity_Available']=pd.to_numeric(df['Quantity_Available'],errors='coerce')
df['Quantity_Available']

0       125.0
1       135.0
2       215.0
3       163.0
4       167.0
        ...
5166    186.0
5167    162.0
5168     88.0
5169    164.0
5170    192.0
Name: Quantity_Available, Length: 5171, dtype: float64

In [7]:
missing_values= df.isnull().sum()
print(missing_values[missing_values>0])

City                     62
Product_Name             73
Quantity_Available        8
Revenue                  72
Supplier                 68
Customer_Satisfaction    77
Delivery_Time            60
dtype: int64

In [8]:
print(df['City'].fillna(df['City'].mode()[0]))

0          Pune
1        Mumbai
2          Pune
3       Chennai
4       Chennai
         ...
5166    Jaipur
5167    Mumbai
5168    Kanpur
5169    Mumbai
5170     Delhi
Name: City, Length: 5171, dtype: str

In [9]:
df['Revenue']

0          7320
1          1645
2         66340
3         77748
4       1976364
         ...
5166      16611
5167       2808
5168     982202
5169     244244
5170    1408680
Name: Revenue, Length: 5171, dtype: str

In [10]:
df['Revenue'] = pd.to_numeric(df['Revenue'],errors='coerce')
df['Revenue']

0          7320.0
1          1645.0
2         66340.0
3         77748.0
4       1976364.0
          ...
5166      16611.0
5167       2808.0
5168     982202.0
5169     244244.0
5170    1408680.0
Name: Revenue, Length: 5171, dtype: float64

In [11]:
df['Revenue'].fillna(
    df['Revenue'].mean(), 
    inplace=True
    )

C:\Users\hp\AppData\Local\Temp\ipykernel_14304\1417158233.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Revenue'].fillna(

0          7320.0
1          1645.0
2         66340.0
3         77748.0
4       1976364.0
          ...
5166      16611.0
5167       2808.0
5168     982202.0
5169     244244.0
5170    1408680.0
Name: Revenue, Length: 5171, dtype: float64

In [12]:
print(df['City'].mode())

0    Delhi
Name: City, dtype: str

In [14]:
duplicates = df.duplicated().sum()
print("Duplicate rows are ",duplicates)

Duplicate rows are  25

In [16]:
df.shape

(5171, 47)

In [18]:
df.drop_duplicates()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [19]:
df=df.drop_duplicates()

In [21]:
df.shape

(5146, 47)