In [16]:
import numpy as np
import pandas as pd

In [17]:
df=pd.read_csv("Retail_Dataset_Cleaned.csv")

In [18]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [19]:
df.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5141,Bx_Jaipur_077,Brandx_India Style Jaipur,Brandx_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150.0,11,2024,Q4,Winter
5142,Bx_Mumbai_067,Brandx_India Daily Mumbai,Brandx_India,Express,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136.0,7,2023,Q3,Monsoon
5143,Bx_Kanpur_097,Brandx_India Gadget Zone Kanpur,Brandx_India,Flagship,Kanpur,Tier2,Dell Xps 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222.0,7,2023,Q3,Monsoon
5144,Bx_Mumbai_031,Brandx_India Style Mumbai,Brandx_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138.0,12,2022,Q4,Winter
5145,Bx_Delhi_032,Brandx_India Electronics Delhi,Brandx_India,Flagship,Delhi,Metro,Macbook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210.0,6,2024,Q2,Monsoon

In [20]:
df.sample()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
4832,Bx_Mumbai_023,Brandx_India Tech Hub Mumbai,Brandx_India,Flagship,Mumbai,Metro,Lg Oled 55Inch,Electronics,Smart Tvs,Discontinued,...,82.9,84.9,Aggressive,Low,3.0,183.0,11,2024,Q4,Winter

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   str
 1   Store_Name             5146 non-null   str
 2   Brand_Name             5146 non-null   str
 3   Store_Type             5146 non-null   str
 4   City                   5146 non-null   str
 5   City_Tier              5146 non-null   str
 6   Product_Name           5146 non-null   str
 7   Category               5146 non-null   str
 8   Sub_Category           5146 non-null   str
 9   Product_Stage          5146 non-null   str
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   str
 20  Sales_Channel          5146 non-null   str
 21  Payment_Method         5146 non-null   str
 22  Supplier               5146 non-null   str
 23  Supplier_Rating        5146 non-null   str
 24  Promotion_Type         5146 non-null   str
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   str
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   str
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   str
 40  Weather_Impact         5146 non-null   str
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   str
 46  Season                 5146 non-null   str
dtypes: float64(15), int64(10), str(22)
memory usage: 1.8 MB

In [22]:
df['Revenue']

0          7320.0
1          1645.0
2         66340.0
3         77748.0
4       1976364.0
          ...
5141      16611.0
5142       2808.0
5143     982202.0
5144     244244.0
5145    1408680.0
Name: Revenue, Length: 5146, dtype: float64

In [23]:
df['Revenue'] = pd.to_numeric(df['Revenue'], errors='coerce')

In [24]:
df['Revenue']

0          7320.0
1          1645.0
2         66340.0
3         77748.0
4       1976364.0
          ...
5141      16611.0
5142       2808.0
5143     982202.0
5144     244244.0
5145    1408680.0
Name: Revenue, Length: 5146, dtype: float64

In [25]:
df.groupby('City')['Revenue'].sum()

City
Ahmedabad        2.655276e+08
Bangalore        8.407997e+08
Bhopal           1.079895e+08
Chennai          7.419116e+08
Delhi            1.661122e+09
Hyderabad        6.597958e+08
Jaipur           2.670945e+08
Kanpur           8.430218e+07
Lucknow          9.486221e+07
Mumbai           1.674840e+09
Nagpur           7.479879e+07
Pune             2.936829e+08
Surat            2.340634e+08
Visakhapatnam    8.106636e+07
Name: Revenue, dtype: float64

In [26]:
category_revenue = pd.pivot_table(df,values="Revenue",index="Category",aggfunc="sum")

In [27]:
category_revenue

                      Revenue
Category
Clothes          2.220630e+08
Electronics      3.623063e+09
Gadgets          2.654379e+09
Groceries        2.394028e+07
Home Appliances  5.584119e+08

In [28]:
category_summary = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc=["sum", "mean", "max", "min"]
)

category_summary

                          sum          mean         max       min
                      Revenue       Revenue     Revenue   Revenue
Category
Clothes          2.220630e+08  1.717425e+05   1245972.0    4985.0
Electronics      3.623063e+09  2.769926e+06  11182353.0  120655.0
Gadgets          2.654379e+09  2.594701e+06  23343582.0    9295.0
Groceries        2.394028e+07  2.365641e+04    350176.0     840.0
Home Appliances  5.584119e+08  1.094925e+06   6588592.0   81333.0

In [29]:
channel_summary = pd.pivot_table(
    df,
    values="Units_Sold",
    index="Sales_Channel",
    aggfunc=["sum", "mean"]
)

channel_summary

                                    sum       mean
                             Units_Sold Units_Sold
Sales_Channel
Brandx_India App                45472.0  44.190476
Brandx_India Online             44598.0  43.982249
Brandx_India Phone Order        44919.0  44.342547
Brandx_India Social Commerce    44695.0  45.329615
Brandx_India Store              48799.0  44.201993

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   str
 1   Store_Name             5146 non-null   str
 2   Brand_Name             5146 non-null   str
 3   Store_Type             5146 non-null   str
 4   City                   5146 non-null   str
 5   City_Tier              5146 non-null   str
 6   Product_Name           5146 non-null   str
 7   Category               5146 non-null   str
 8   Sub_Category           5146 non-null   str
 9   Product_Stage          5146 non-null   str
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   str
 20  Sales_Channel          5146 non-null   str
 21  Payment_Method         5146 non-null   str
 22  Supplier               5146 non-null   str
 23  Supplier_Rating        5146 non-null   str
 24  Promotion_Type         5146 non-null   str
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   str
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   str
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   str
 40  Weather_Impact         5146 non-null   str
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   str
 46  Season                 5146 non-null   str
dtypes: float64(15), int64(10), str(22)
memory usage: 1.8 MB

In [31]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring